version: "3"
services:
  db:
    image: mysql:latest
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always

    environment:
      MYSQL_DATABASE: "trainee_management"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/trainee_management
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
