# Generated by Django 3.0.4 on 2020-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue_name', models.CharField(max_length=100, unique=True)),
                ('venue_mobile', models.CharField(max_length=20, unique=True)),
                ('venue_email', models.EmailField(max_length=50, unique=True)),
                ('venue_total_room', models.IntegerField()),
                ('venue_total_capacity', models.IntegerField()),
                ('venue_address', models.TextField()),
                ('venue_status', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
