# Generated by Django 3.0.4 on 2020-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_status',
            field=models.IntegerField(default=1),
        ),
    ]
