# Generated by Django 3.0.4 on 2020-03-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200326_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('course_duration', models.IntegerField()),
                ('course_fee', models.IntegerField()),
                ('course_content', models.TextField()),
                ('course_status', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
