# Generated by Django 3.0.4 on 2020-03-31 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.IntegerField(unique=True)),
                ('birth_reg_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('gender', models.BooleanField(default=1)),
                ('religion', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('exp_years', models.IntegerField(default=0)),
                ('nationality', models.CharField(max_length=100)),
                ('level_of_education', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='trainer/')),
                ('is_foreign_trainer', models.BooleanField(default=0)),
                ('is_guest_trainer', models.BooleanField(default=0)),
                ('area_of_expertise', models.TextField()),
                ('list_of_expertise', models.TextField()),
                ('is_bteb_registered', models.BooleanField(default=0)),
                ('bteb_register_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Trainer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
